name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # issue-message: 'TODO: Message that will be displayed on users'' first issue'
        pr-message: 'Thanks for being interested in improving Enumpath! We welcome all kinds of contributions. There are a couple of things you should know before contributing to this repository, so be sure to [read our contributing guide](https://github.com/chrisbloom7/enumpath/blob/master/CONTRIBUTING.md) while awaiting feedback.'
